package com.ttdev.biz;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import com.ttdev.biz.ProductQueryComplexType.QueryItem;
import com.ttdev.biz.ProductQueryResult.ResultItem;

/**
 * This class was generated by Apache CXF 2.6.2 2012-12-31T15:14:19.139+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class BizService_BizServiceSOAP_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://svashishtha.com/ws", "BizService");

	private BizService_BizServiceSOAP_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = BizService_Service.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		BizService_Service ss = new BizService_Service(wsdlURL, SERVICE_NAME);
		BizService port = ss.getBizServiceSOAP();

		{
			com.ttdev.biz.ProductQueryComplexType _query_parameters = new ProductQueryComplexType();
			QueryItem item = new QueryItem();
			item.setProductId("p01");
			item.setQty(100);
			_query_parameters.getQueryItem().add(item);
			item = new QueryItem();
			item.setProductId("p02");
			item.setQty(200);
			_query_parameters.getQueryItem().add(item);
			item = new QueryItem();
			item.setProductId("p03");
			item.setQty(500);
			_query_parameters.getQueryItem().add(item);
			com.ttdev.biz.ProductQueryResult _query__return = port
					.query(_query_parameters);
			for (ResultItem resultItem : _query__return.getResultItem()) {
				System.out.println(resultItem.getProductId() + ": "
						+ resultItem.getPrice());
			}

		}

		System.exit(0);
	}

}
