
package com.svashishtha.service.img;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-31T15:28:01.497+08:00
 * Generated source version: 2.6.2
 * 
 */
 
public class ImageService_P1_Server{

    protected ImageService_P1_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ImageServiceImpl();
        String address = "http://localhost:8080/is/p1";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ImageService_P1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
