package com.svashishtha.service.img;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-31T15:28:01.465+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "urn:svashishtha.com:service/img", name = "ImageService")
@XmlSeeAlso({ObjectFactory.class})
public interface ImageService {

    @Oneway
    @RequestWrapper(localName = "uploadImage", targetNamespace = "urn:svashishtha.com:service/img", className = "com.svashishtha.service.img.UploadImage")
    @WebMethod(action = "urn:svashishtha.com:service/img/uploadImage")
    public void uploadImage(
        @WebParam(name = "productId", targetNamespace = "")
        java.lang.String productId,
        @WebParam(name = "image", targetNamespace = "")
        byte[] image
    );
}
