package com.ttdev.biz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-31T14:57:20.551+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://svashishtha.com/ws", name = "BizService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BizService {

    @WebResult(name = "productQueryResult", targetNamespace = "http://svashishtha.com/ws", partName = "parameters")
    @WebMethod(action = "http://svashishtha.com/ws/BizService/NewOperation")
    public ProductQueryResult query(
        @WebParam(partName = "parameters", name = "productQuery", targetNamespace = "http://svashishtha.com/ws")
        ProductQueryComplexType parameters
    );
}
