package com.ttdev.biz;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-31T14:57:20.585+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "BizService", 
                  wsdlLocation = "src/main/resources/BizService.wsdl",
                  targetNamespace = "http://svashishtha.com/ws") 
public class BizService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://svashishtha.com/ws", "BizService");
    public final static QName BizServiceSOAP = new QName("http://svashishtha.com/ws", "BizServiceSOAP");
    static {
        URL url = BizService_Service.class.getResource("src/main/resources/BizService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(BizService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "src/main/resources/BizService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public BizService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BizService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BizService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BizService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BizService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BizService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BizService
     */
    @WebEndpoint(name = "BizServiceSOAP")
    public BizService getBizServiceSOAP() {
        return super.getPort(BizServiceSOAP, BizService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BizService
     */
    @WebEndpoint(name = "BizServiceSOAP")
    public BizService getBizServiceSOAP(WebServiceFeature... features) {
        return super.getPort(BizServiceSOAP, BizService.class, features);
    }

}
