
package com.svashishtha.ws;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-01-01T08:38:56.473+08:00
 * Generated source version: 2.6.2
 * 
 */
 
public class ComputeService_P1_Server{

    protected ComputeService_P1_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ComputeServiceImpl();
        String address = "http://localhost:8080/ws/p1";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ComputeService_P1_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
