package com.svashishtha.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-01-01T08:38:56.444+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://svashishtha.com/ws", name = "ComputeService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ComputeService {

    @WebResult(name = "computeResponse", targetNamespace = "http://svashishtha.com/ws", partName = "parameters")
    @WebMethod(action = "http://svashishtha.com/ws/compute")
    public java.lang.String compute(
        @WebParam(partName = "parameters", name = "compute", targetNamespace = "http://svashishtha.com/ws")
        java.lang.String parameters
    );
}
