package com.svashishtha.service.img;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.2 2012-12-31T15:32:34.687+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class ImageService_P1_Client {

	private static final QName SERVICE_NAME = new QName(
			"urn:svashishtha.com:service/img", "ImageService");

	private ImageService_P1_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = ImageService_Service.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		ImageService_Service ss = new ImageService_Service(wsdlURL,
				SERVICE_NAME);
		ImageService port = ss.getP1();

		{
			System.out.println("Invoking uploadImage...");
			java.lang.String _uploadImage_productId = "p01";
			FileInputStream in = new FileInputStream(
					"src/main/resources/sample.jpg");
			ByteArrayOutputStream out = new ByteArrayOutputStream();
			byte[] buf = new byte[1024];
			for (;;) {
				int noBytesRead = in.read(buf);
				if (noBytesRead == -1) {
					break;
				}
				out.write(buf, 0, noBytesRead);
			}
			port.uploadImage(_uploadImage_productId, out.toByteArray());
			out.close();
			in.close();

		}

		System.exit(0);
	}

}
