
package com.svashishtha.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-12-31T13:24:30.494+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class WrappedService_P1_Client {

    private static final QName SERVICE_NAME = new QName("http://svashishtha.com/ws", "WrappedService");

    private WrappedService_P1_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WrappedService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WrappedService_Service ss = new WrappedService_Service(wsdlURL, SERVICE_NAME);
        WrappedService port = ss.getP1();  
        
        {
        System.out.println("Invoking concat...");
        java.lang.String _concat_s1 = "First Value";
        java.lang.String _concat_s2 = "\nSecond Value";
        java.lang.String _concat__return = port.concat(_concat_s1, _concat_s2);
        System.out.println("concat.result=" + _concat__return);


        }

        System.exit(0);
    }

}
